# This is a basic workflow that is manually triggered

name: Weekly Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Build Weekly
      id: build_weekly
      run: ant -noinput -buildfile weekly.xml
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: Build-${{ github.run_number  }}
          release_name:  Build-Weekly-${{ github.run_number  }}
          body: |
            ![Java CI](https://github.com/NPEX42/NPlib/workflows/Java%20CI/badge.svg) 
            Weekly Build
          draft: false
          prerelease: true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
          tag: Build-${{ github.run_number  }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/NPlib-weekly.jar
          asset_name: NPlib-Weekly  
